services:
  order-db:
    ports:
      - '27017:27017'
    container_name: order-db
    restart: always
    networks:
      - orchestrator-saga
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    image: mongo:latest

  order-service:
    build: './order-service'
    container_name: order-service
    depends_on:
      - order-db
    networks:
      - orchestrator-saga
    environment:
      - MONGO_DB_URI=mongodb://admin:123456@order-db:27017
    ports:
      - 3000:3000


networks:
  orchestrator-saga:
    driver: bridge