server:
  port: 3000

spring:

  kafka:
    bootstrap-servers: ${KAFKA_BROKER}
    topic:
      notify-ending: notify-ending
      start-saga: start-saga
    consumer:
      group-id: order-group
      auto-offset-reset: latest

  data:
    mongodb:
      database: admin
      uri: ${MONGO_DB_URI}